### ISSUE TITLE
유닛 존재 처리 코드 이동

### ISSUE THREAD

**Issue by dongcheolpark** [GAMPOT-DEV/TEAM_1#19]
현재 PlaceManager.cs 20번째줄에 있는 유닛 존재 처리 코드를 UnitManager.cs로 옮겨야 할 것 같습니다. PlaceManager는 보드의 기능을 담당하고 UnitManager는 유닛의 생성,제거,이동과 관련이 있기 때문에 UnitManager가 담당하는 것이 더 효율적일 것 같습니다.

**Comment by Yeogiwon** [comment]
넵넵 수정해 놓을게용
