### ISSUE TITLE
Move했던 자리에 유닛 생성이 되지 않는 버그

### ISSUE THREAD

**Issue by dongcheolpark** [GAMPOT-DEV/TEAM_1#21]
move를 했던 자리에서 유닛생성이 되지 않는 버그가 있습니다.

**Comment by kjhcocomi** [comment]
지금 유닛들이 자리를 이동할 때 좌표를 통해 바꿔주다 보니 바꿔야 할 정보들이 꽤 많아서 전에 있던 자리의 isEmpty를 true로 바꿔주지 않아서 발생한 버그인것 같습니다.

유닛마다 PlaceObject 객체를 물고 있게 바꾸는 것은 어떨까요?
1. 처음 유닛의 PlaceObject는 null
2. 배치시키면 유닛의 PlaceObject 에 배치된 PlaceObject를 할당하고 해당 PlaceObject의 isEmpty를 false로 바꿔준다.
3. 이동시키면 현재 유닛의 PlaceObject의 isEmpty를 true로 바꿔주고 이동시킬 PlaceObject를 유닛에 새로 할당하고 isEmpty를 false로 바꿔준다.

괜찮은 것 같다고 생각하시면 제가 한번 수정해 보겠습니다.

**Comment by dongcheolpark** [comment]
저는 좋을 것 같아요. 진행 하셔도 괜찮을 것 같습니다.

**Comment by kjhcocomi** [comment]
넵 밥좀 먹고 해보겠습니다.

**Comment by dongcheolpark** [comment]
넵
