### ISSUE TITLE
Move _currSelectUnit이 이상하게 잡히는 현상이 있습니다.

### ISSUE THREAD

**Issue by dongcheolpark** [GAMPOT-DEV/TEAM_1#25]
_currSelectUnit의 PlaceObject가 Null로 나오는 현상이 있습니다.

**Comment by kjhcocomi** [comment]
이미 배치되어있는 유닛 중 어떤 유닛을 클릭했는지 볼 수 있게 만든거라 유닛을 배치하고 클릭하기 전에는 null이긴 합니다.
이 경우 말고 다른 경우에도 그런 현상이 있는건가요?

**Comment by dongcheolpark** [comment]
찾은것 같습니다. PlaceObject 가 Unit 안에 정의되어 있는데 GetComponent로 가져온거다 보니 GC가 바로 버리는것 같아요. GameObject로 변경하도록 하겠습니다.

**Comment by dongcheolpark** [comment]
PlaceObject 의 OnMouseDown()
```cs
if (click_state >= InputManager.E_CLICKERSTATE.CREATEUNIT1 &&
            click_state <= InputManager.E_CLICKERSTATE.CREATEUNIT4)
        {
            _unitManager.CreateUnit(this, "Unit");
            Debug.Log($"Create : {click_state}");
        }
```

여기서 this가 문제를 발생시키는 듯 합니다. 계속 GC가 지우는것 같은데 이거 깊은 복사처리하면 해결이 될까요?

**Comment by dongcheolpark** [comment]
아마 해결하려면 OnMouseDown의 this로 처리하지 말고 Input에서 GetComponent로 가져와서 붙여야 될것같아요

**Comment by dongcheolpark** [comment]
찾아보니까 그냥 parent로 붙이라고해서 한번 붙여보겠습니다

**Comment by dongcheolpark** [comment]
해결햇습니다. prefabs에 Unit.cs가 잡혀있어서 생긴 문제였습니다.
