### ISSUE TITLE
Input들 InputManager로 이동

### ISSUE THREAD

**Issue by dongcheolpark** [GAMPOT-DEV/TEAM_1#26]
현재 입력을 각각 오브젝트 안에서 OnMouseDown으로 처리하는데 이걸 InputManager안으로 통합해 보고 싶습니다.

- InputManager에서 오브젝트 관한 입력받기
- 이를 SceneManager로 넘겨서 게임 로직 작성
- SceneManager는 UnitManager나 PlaceManager의 함수들을 호출해 가며 게임의 흐름 관리

이렇게 바꾸고 싶은데 어떻게 생각하시나요?

**Comment by kjhcocomi** [comment]
그리고 InputManager 안에서 OnMouseDown을 쓰기는 힘들 것 같아서 우선순위를 두고 RayCast를 이용하면 좋을 것 같습니다.
ex) place랑 unit이 있으면 unit의 우선순위를 높게 하고 z좌표를 조금 앞쪽에 배치해서 레이저를 먼저 맞게 함

**Comment by dongcheolpark** [comment]
네 좋아요~
