### ISSUE TITLE
start함수 관련 문제

### ISSUE THREAD

**Issue by dongcheolpark** [GAMPOT-DEV/TEAM_1#45]
모든 매니저에서 각각 start를 호출하다보니까 실행 순서가 명확하지 않아서 생기는 문제가 있습니다. start함수를 GameManager start 안으로 통일 시키는건 어떨까요?

**Comment by Yeogiwon** [comment]
넵 매니저에서 start하는 애들은 통일 시키도록 하져

**Comment by kjhcocomi** [comment]
각 매니저에서 초기화하는 부분을 Init 함수로 만들고 GameManager에서 순서에 맞춰서 호출하면 될 것 같습니다.
