### ISSUE TITLE
플레이어 싱글톤 관련

### ISSUE THREAD

**Issue by dongcheolpark** [GAMPOT-DEV/TEAM_1#52]
플레이어 코드에 싱글톤이 있는걸 확인했는데 굳이 싱글톤으로 하지말고 SceneManager에 맴버 변수로 추가하는게 조금 더 효율적일 것 같습니다. 두가지 안 모두 pr 올려두겠습니다.

**Comment by dongcheolpark** [comment]
그럼 일단 현재 pr 올려둔건 내리겠습니다

**Comment by dongcheolpark** [comment]
유닛 능력 코드에 싱글톤 활용한 코드를 확인했는데 제 생각에는 [중재자](https://narakit.tistory.com/76)패턴처럼 SceneManager에 Player 능력 증감 함수를 만들고 그걸로 상호작용하는게 더 나아보입니다. 그렇게 바꾸어도 될까요?

**Comment by kjhcocomi** [comment]
제가 작성한 코드가 아니라서 잘 모르겠네요
