### ISSUE TITLE
전체적인 구조에 대하여

### ISSUE THREAD

**Issue by kjhcocomi** [GAMPOT-DEV/TEAM_1#71]
게임 진행 방식이 로비화면 씬에서 스테이지를 클릭하면 배틀 씬으로 넘어가서 배틀을 하는 방식으로 알고 있습니다.
여러 스테이지가 있으니 로비화면 씬과 배틀화면 씬을 여러번 왔다갔다 하면서 플레이 하겠죠?

그런데 지금 Manager들은 배틀 씬 전용으로 만들어져있고 일단 Dontdestroyonload를 적용해놔서 씬을 이동해도 사라지지 않습니다. 
제가 해놓긴 했는데 생각해보니 로비화면 씬이나 다른 씬에서 배틀 씬 전용인 이 매니저들이 유지되는 것은 적절하지 않다고 생각합니다.

그래서 저는 게임을 시작할 때 맨 처음 씬에서 Player를 만들고 이것을 Dontdestroyonload를 적용해서 모든 씬에서 유지될 수 있도록 하고, 배틀 씬으로 이동할 때마다 새로운 매니저가 새로 생기도록 냅두고, 이때 필요한 정보는 Player을 통해서 전달하는 방식으로 만들면 어떨까 생각을 해봤습니다.

예) 
1. Player에 현재 해금한 스테이지와 유닛을 저장하고 로비 화면 씬에 왔을 때는 Player에 저장되어있는 해금한 스테이지의 정보와 UI를 연동해서 들어갈 수 있는 스테이지를 표시한다. 
2. 스테이지를 누르면 누른 스테이지 번호를 Player에 저장하고 배틀 씬으로 이동해서 누른 스테이지 번호에 따라 스테이지의 배경/ 적들의 로직 등을 정한다.
3.  배틀 씬으로 이동하면 Player의 유닛 해금 정보와 유닛 소환 UI를 연동해서 소환할 수 있는 유닛과 할 수 없는 유닛을 구분한다.

요약)
1. 현재 배틀 씬 전용으로 만들어진 Manager들은 Dontdestroyonload를 사용하기에 부적합하다고 판단됨, 배틀 씬에 들어갈 때마다 매니저가 생기도록 변경한다.
2. Player에 필요한 정보들을 담아서 맨 처음 씬에서 Dontdestroyonload를 적용해서 모든 씬에서 사용할 수 있게 한다.
3. 씬을 이동할 때마다 Player의 정보와 연동해서 화면을 표시하게 한다.

비유하자면 Manager들은 배틀 씬의 싱글톤, Player는 전체 게임의 싱글톤? 이라고 볼 수 있겠네요.

일단 이게 제 생각인데 다른분들은 어떻게 생각하시나요?

**Comment by dongcheolpark** [comment]
네 저도 종현님 의견이 맞는 것 같다고 생각합니다

**Comment by dongcheolpark** [comment]
대신에 이름만 player말고 다른 것으로 하는 건 어떨까요? 이미 Player 클래스가 있다 보니 헷갈릴 것 같아요. 할 수 있다면 본문의 Player 클래스가 세이브 파일 불러오는 것도 담당하면 좋을 것 같아요.

**Comment by kjhcocomi** [comment]
지금 있는 Player를 없애고 새로운 Player를 만들려고 한건데 다른 정보들도 포함해야하니 다른 이름으로 변경하는 것도 괜찮을 것 같네요.

**Comment by kjhcocomi** [comment]
내일부터 작업 시작하겠습니다.

**Comment by dongcheolpark** [comment]
넵
