### ISSUE TITLE
AI 알고리즘

### ISSUE THREAD

**Issue by dongcheolpark** [GAMPOT-DEV/TEAM_1#82]
AI에 들어갈 알고리즘을 설계해야 하는데 여러 방법이 있을 것 같습니다.
- 랜덤으로 아무 유닛 배치
- 유닛 별로 점수를 매겨 탐욕(greedy) 알고리즘
- bfs로 가장 이상적인 행동 선택
- [minimax 알고리즘](https://popungpopung.tistory.com/10)

기타 여러 의견 부탁드립니다~!

**Comment by kjhcocomi** [comment]
랜덤이나 그리디가 괜찮을 것 같습니다
